### PR TITLE
doc: add compressdev programmers guide

### PR DESCRIPTION
**Pull request by ashishgupta4**
Add programmer’s guide for compress dev library.

Here's an updated programmer guides with
- review inputs
-  description for hash support in compression API

ToDo:
- @pablo  Please add priv_data_size and description in device init example under section "Device  Creation" as we are not clear with its expected usage.

Signed-off-by: Shally Verma <shally.verma@caviumnetworks.com>
Signed-off-by: Sunila Sahu <sunila.sahu@caviumnetworks.com>
Signed-off-by: Ashish Gupta <ashish.gupta@caviumnetworks.com>

### CODE REVIEW

**Comment by pablodelara** [comment]
@ashishgupta4 priv_data_size is used internally for the PMDs to provide how much space it is needed for the private data (stored in dev->data->dev_private). Pointers to mempools for private xforms and streams are expected to be included here.

**Comment by 1234sv** [comment]
As i understand rte_vdev_init() is called from applications for virtual devices, so how a test application know device private data size? Should it internally be known within device itself? What am I missing here?

**Comment by 1234sv** [comment]
Minor correction to comment above. I meant - Shouldn't it internally be known within device itself?

**Comment by 1234sv** [comment]
I assume this doc will be merged to github and taken for next patch or Do I need to send it to ML separately?

**Comment by pablodelara** [comment]
Correct, this will go into the next version of the API.
We still need to finish the review of it, but basically you don't have to send it separately.
Thanks!

**Pull request closed without merging**
