### PR TITLE
Out of space clarification

### PR DESCRIPTION
**Pull request by fionatrahe**
Hi all,

I’m trying to describe what we agreed re OUT_OF_SPACE (on 16/2):
>> [Fiona] That's not quite how I understood it. Can it be simpler and only following cases?
>> a. stateless with flush = full/final, no stream pointer provided , PMD can return TERMINATED i.e. user
>>     has to start all over again, it's a failure (as in current definition).
>>     consumed = 0, produced=amount of data produced. This is usually 0, but in decompression
>>     case a PMD may return > 0 and application may find it useful to inspect that data.
>> b. stateless with flush = full/final, stream pointer provided, here it's up to PMD to return either
>>     TERMINATED or RECOVERABLE depending upon its ability (note if Recoverable, then PMD will maintain
>>     states in stream pointer)
>> c. stateful with flush = any, stream pointer always there, PMD will return RECOVERABLE.
>>     op.produced can be used and next op in stream should continue on from op.consumed+1.
>>     Consumed=0, produced=0 is an unusual but allowed case. I'm not sure if it could ever happen, but
>>     no need to change state to TERMINATED in this case. There may be useful state/history
>>     stored in the PMD, even though no output produced yet.
>[Ahmed] Agreed
[Shally] Sounds good.

(a) and (c) are ok - covered in this patch.
I was going to write this to cover (b), but can’t see how it can work?
 * Typically OUT_OF_SPACE_RECOVERABLE is only returned on STATEFUL ops, however
 * a PMD may return this on a STATELESS op if it is capable of continuing on.
 * In this case it must be using a NOT_SHAREABLE private_xform in which it
 * stored the history and state, so enabling it to continue.

Can this work? 
How does the PMD know how to relate the next op to the history and state of the last op?
And couldn't the appl attach the private_xform to some other op, once the first op is complete? And then the history would be overwritten - i.e would the application need to know to NOT re-use the private_xform in this case?
But then what if the appl doesn't try to recover and resubmits from the start how will the PMD know NOT to use the history?
And when will the history get cleared?

Or would it work like a flush full? i.e. the PMD produces output which is decompressible, i.e. finishes the deflate block, no history or state stored, it can continue from consumed+1 but next output will not depend on previous. Like 2 sequential stateless ops on sequential data. No need for PMD to be aware of the link between the 2 ops.
This sounds like it could work.

I’ll leave out for v2 – we can add in v3 if there’s a valid case.

### CODE REVIEW

**Comment by ahmedmpr** [comment]
Hi @fionatrahe ,

Case b) only provides an advantage if the stream is allocated on the fly. Not by the  PMD. It must be a HW functionality. Otherwise there is no point in moving this mode of use from the application layer into the PMD layer. The advantage would be that stream state memory need only be allocated once an exception actually occurs.

A system (PMD + HW) must have some memory pool from which the HW can allocate.

> How does the PMD know how to relate the next op to the history and state of the last op?

The op must come back with a stream pointer that identifies which stream that was dynamicaly allocated that it belongs to. 

> And couldn't the appl attach the private_xform to some other op, once the first op is complete? And then the history would be overwritten - i.e would the application need to know to NOT re-use the private_xform in this case?

the private_xform remains a generic all op STATELESS use. The op that experienced an interruption came back with a stream that is unique and should be used for it if continuing is desired. This would be like normal STATEFUL use

> But then what if the appl doesn't try to recover and resubmits from the start how will the PMD know NOT to use the history?

The application will use the same mechanism it used initially to add memory to the HW memory pool in the first place. i.e. returning memory to the HW pool is like allocating it initially. Whether the application used the stream or ignored it and resent the work is not of concern to the PMD

> And when will the history get cleared?

Never by the PMD or the HW. The hard limit is the size of the HW pool. If the application did not allocate any then the HW will simply do not STATELESS and always return TERMINATED in exception cases. If the application unintentionally leaks then the upper limit is the pool it pre-allocated and soon the leak will manifest

> Or would it work like a flush full? i.e. the PMD produces output which is decompressible, i.e. finishes the deflate block, no history or state stored, it can continue from consumed+1 but next output will not depend on previous. Like 2 sequential stateless ops on sequential data. No need for PMD to be aware of the link between the 2 ops.
This sounds like it could work.

I am not sure I understand your comment fully. STATELESS always means Z_FINISH. if an op is returned RECOVERABLE then the application will treat it as STATEFUL afterwards

> I’ll leave out for v2 – we can add in v3 if there’s a valid case.

Agreed. Case b) can be implemented in the SW PMD layer. Maybe I am wrong, but I do not see an advantage unless it is part of the HW design. I do not know of HW which supports this today, so v3 or later is good. The only reason to investigate b) is to make the API more future proof and maybe I am overreaching. The main concern for me is that the same return status code OUT_OF_SPACE meant two different things. Now the addition of _RECOVERABLE vs _TERMINATED clarifies that and I can sleep better at night :)

**Comment by fionatrahe** [comment]
ok. I see what you mean by the stream being allocated by the HW or firmware in the exception case. 
But the op would need to return a stream handle as wella s the RECOVERABLE status in this case, and the op doesn't currently have this handle.
So I don't plan to change the API to handle this case or document it. If someone has a convincing case for it in future they can submit a proposal.

**Comment by pablodelara** [comment]
Merging this manually, as the only commit useful is the last one.

**Comment by ahmedmpr** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

**Pull request closed without merging**
